"""200 个 SOTA 策略配置目录 — 100 加密货币 + 100 期货。

每个配置包含:
- account_id: 账号编号
- class_path: 策略类的导入路径
- params: 策略独特的参数集
- symbols: 交易品种
- description: 策略学术/实践来源描述

策略家族覆盖:
Crypto (1-100): Kalman/Supertrend/KAMA/Hull/DEMA/VolTarget/TSMOM/DualMom/
  Z-Score/Regime/OrderFlow/MultiIndicator/Channel/Momentum/TrendFollow/MeanRevert/Grid/ML
Futures (101-200): CTA/R-Breaker/DualMA/Bollinger/VolBreak/Supertrend/Kalman/Regime/
  Channel/VWAP/StatArb/MultiIndicator/VolTarget/AdaptiveTrend/MomRotation
"""

from __future__ import annotations

from typing import Any


def _entry(
    account_id: int,
    cls: str,
    name: str,
    symbols: list[str],
    params: dict[str, Any],
    desc: str = "",
) -> dict[str, Any]:
    return {
        "account_id": account_id,
        "class_path": cls,
        "name": name,
        "symbols": symbols,
        "params": params,
        "description": desc,
    }


# ── 加密货币品种 ──
CRYPTO_SYMS_BTC = ["BTCUSDT"]
CRYPTO_SYMS_ETH = ["ETHUSDT"]
CRYPTO_SYMS_BNB = ["BNBUSDT"]
CRYPTO_SYMS_SOL = ["SOLUSDT"]
CRYPTO_SYMS_XRP = ["XRPUSDT"]
CRYPTO_SYMS_ALL = ["BTCUSDT", "ETHUSDT", "BNBUSDT"]

# ── 期货品种 ──
FUT_RB = ["rb2510"]  # 螺纹钢
FUT_I = ["i2509"]    # 铁矿石
FUT_MA = ["MA2509"]  # 甲醇
FUT_AG = ["ag2512"]  # 白银
FUT_AU = ["au2512"]  # 黄金
FUT_CU = ["cu2509"]  # 铜
FUT_AL = ["al2509"]  # 铝
FUT_NI = ["ni2509"]  # 镍
FUT_ZN = ["zn2509"]  # 锌
FUT_IF = ["IF2506"]  # 沪深300股指
FUT_IC = ["IC2506"]  # 中证500股指
FUT_TA = ["TA2509"]  # PTA
FUT_PP = ["pp2509"]  # 聚丙烯

# ══════════════════════════════════════════════
# CRYPTO STRATEGIES (accounts 1-100)
# ══════════════════════════════════════════════

CRYPTO_CATALOG: list[dict[str, Any]] = [
    # ─── Kalman Filter Trend (1-8) ───
    _entry(1, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-BTC-Fast",
           CRYPTO_SYMS_BTC, {"process_noise": 0.02, "measurement_noise": 0.3, "velocity_threshold": 0.002, "max_hold_bars": 100},
           "Kalman快速趋势 (高灵敏度)"),
    _entry(2, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-BTC-Slow",
           CRYPTO_SYMS_BTC, {"process_noise": 0.005, "measurement_noise": 1.0, "velocity_threshold": 0.0005, "max_hold_bars": 300},
           "Kalman慢速趋势 (低噪声)"),
    _entry(3, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-ETH-Fast",
           CRYPTO_SYMS_ETH, {"process_noise": 0.015, "measurement_noise": 0.4, "velocity_threshold": 0.0015},
           "Kalman ETH 快速"),
    _entry(4, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-ETH-Balanced",
           CRYPTO_SYMS_ETH, {"process_noise": 0.008, "measurement_noise": 0.6, "velocity_threshold": 0.001},
           "Kalman ETH 均衡"),
    _entry(5, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-BNB",
           CRYPTO_SYMS_BNB, {"process_noise": 0.012, "measurement_noise": 0.5, "velocity_threshold": 0.0012},
           "Kalman BNB"),
    _entry(6, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-SOL-Aggressive",
           CRYPTO_SYMS_SOL, {"process_noise": 0.025, "measurement_noise": 0.2, "velocity_threshold": 0.003, "trailing_stop_atr_mult": 1.5},
           "Kalman SOL 激进"),
    _entry(7, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-XRP",
           CRYPTO_SYMS_XRP, {"process_noise": 0.01, "measurement_noise": 0.5, "velocity_threshold": 0.001},
           "Kalman XRP"),
    _entry(8, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-Multi",
           CRYPTO_SYMS_ALL, {"process_noise": 0.01, "measurement_noise": 0.5, "velocity_threshold": 0.001},
           "Kalman 多品种"),

    # ─── Supertrend (9-16) ───
    _entry(9, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-BTC-Standard",
           CRYPTO_SYMS_BTC, {"atr_period": 10, "multiplier": 3.0, "adx_threshold": 20},
           "Supertrend BTC 标准"),
    _entry(10, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-BTC-Tight",
           CRYPTO_SYMS_BTC, {"atr_period": 7, "multiplier": 2.0, "adx_threshold": 15},
           "Supertrend BTC 紧凑"),
    _entry(11, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-BTC-Wide",
           CRYPTO_SYMS_BTC, {"atr_period": 14, "multiplier": 4.0, "adx_threshold": 25},
           "Supertrend BTC 宽带"),
    _entry(12, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-ETH",
           CRYPTO_SYMS_ETH, {"atr_period": 10, "multiplier": 3.0, "adx_threshold": 18},
           "Supertrend ETH"),
    _entry(13, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-SOL",
           CRYPTO_SYMS_SOL, {"atr_period": 8, "multiplier": 2.5, "adx_threshold": 15},
           "Supertrend SOL"),
    _entry(14, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-BNB",
           CRYPTO_SYMS_BNB, {"atr_period": 10, "multiplier": 3.0},
           "Supertrend BNB"),
    _entry(15, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-XRP",
           CRYPTO_SYMS_XRP, {"atr_period": 12, "multiplier": 3.5},
           "Supertrend XRP"),
    _entry(16, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-Multi",
           CRYPTO_SYMS_ALL, {"atr_period": 10, "multiplier": 3.0, "adx_threshold": 22},
           "Supertrend 多品种"),

    # ─── Adaptive Trend KAMA/Hull/DEMA (17-28) ───
    _entry(17, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-BTC-Fast",
           CRYPTO_SYMS_BTC, {"ma_type": "kama", "fast_period": 5, "slow_period": 20, "er_period": 10},
           "Kaufman AMA BTC 快速"),
    _entry(18, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-BTC-Slow",
           CRYPTO_SYMS_BTC, {"ma_type": "kama", "fast_period": 15, "slow_period": 50, "er_period": 20},
           "Kaufman AMA BTC 慢速"),
    _entry(19, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-ETH",
           CRYPTO_SYMS_ETH, {"ma_type": "kama", "fast_period": 8, "slow_period": 30},
           "Kaufman AMA ETH"),
    _entry(20, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-BTC-Fast",
           CRYPTO_SYMS_BTC, {"ma_type": "hull", "fast_period": 9, "slow_period": 21},
           "Hull MA BTC 快速 (Alan Hull)"),
    _entry(21, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-BTC-Slow",
           CRYPTO_SYMS_BTC, {"ma_type": "hull", "fast_period": 16, "slow_period": 36},
           "Hull MA BTC 慢速"),
    _entry(22, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-ETH",
           CRYPTO_SYMS_ETH, {"ma_type": "hull", "fast_period": 12, "slow_period": 28},
           "Hull MA ETH"),
    _entry(23, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "DEMA-BTC",
           CRYPTO_SYMS_BTC, {"ma_type": "dema", "fast_period": 10, "slow_period": 25},
           "DEMA BTC (Patrick Mulloy)"),
    _entry(24, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "DEMA-ETH",
           CRYPTO_SYMS_ETH, {"ma_type": "dema", "fast_period": 12, "slow_period": 30},
           "DEMA ETH"),
    _entry(25, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-SOL",
           CRYPTO_SYMS_SOL, {"ma_type": "kama", "fast_period": 6, "slow_period": 22},
           "Kaufman AMA SOL"),
    _entry(26, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-BNB",
           CRYPTO_SYMS_BNB, {"ma_type": "hull", "fast_period": 10, "slow_period": 24},
           "Hull MA BNB"),
    _entry(27, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-Multi",
           CRYPTO_SYMS_ALL, {"ma_type": "kama", "fast_period": 8, "slow_period": 25},
           "Kaufman AMA 多品种"),
    _entry(28, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-Multi",
           CRYPTO_SYMS_ALL, {"ma_type": "hull", "fast_period": 11, "slow_period": 26},
           "Hull MA 多品种"),

    # ─── Vol Target / TSMOM (29-38) ───
    _entry(29, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-BTC-10",
           CRYPTO_SYMS_BTC, {"target_vol": 0.10, "lookback": 20},
           "VolTarget BTC 10%年化目标 (AQR风格)"),
    _entry(30, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-BTC-15",
           CRYPTO_SYMS_BTC, {"target_vol": 0.15, "lookback": 20},
           "VolTarget BTC 15%"),
    _entry(31, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-BTC-20",
           CRYPTO_SYMS_BTC, {"target_vol": 0.20, "lookback": 30},
           "VolTarget BTC 20%"),
    _entry(32, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-ETH-15",
           CRYPTO_SYMS_ETH, {"target_vol": 0.15, "lookback": 20},
           "VolTarget ETH 15%"),
    _entry(33, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-SOL-20",
           CRYPTO_SYMS_SOL, {"target_vol": 0.20, "lookback": 15},
           "VolTarget SOL 20%"),
    _entry(34, "strategy.templates.vol_target.VolTargetStrategy", "TSMOM-BTC-Short",
           CRYPTO_SYMS_BTC, {"lookback": 10, "target_vol": 0.15, "holding_period": 5},
           "TSMOM BTC 短周期 (Moskowitz et al.)"),
    _entry(35, "strategy.templates.vol_target.VolTargetStrategy", "TSMOM-BTC-Medium",
           CRYPTO_SYMS_BTC, {"lookback": 30, "target_vol": 0.12, "holding_period": 10},
           "TSMOM BTC 中周期"),
    _entry(36, "strategy.templates.vol_target.VolTargetStrategy", "TSMOM-ETH",
           CRYPTO_SYMS_ETH, {"lookback": 20, "target_vol": 0.15},
           "TSMOM ETH"),
    _entry(37, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-Multi",
           CRYPTO_SYMS_ALL, {"target_vol": 0.12, "lookback": 20},
           "VolTarget 多品种组合"),
    _entry(38, "strategy.templates.vol_target.VolTargetStrategy", "TSMOM-Multi",
           CRYPTO_SYMS_ALL, {"lookback": 25, "target_vol": 0.15},
           "TSMOM 多品种"),

    # ─── Z-Score Statistical MR (39-48) ───
    _entry(39, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-BTC-Tight",
           CRYPTO_SYMS_BTC, {"lookback": 30, "entry_z": 1.5, "exit_z": 0.3, "rsi_confirm": True},
           "Z-Score MR BTC 紧入场"),
    _entry(40, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-BTC-Wide",
           CRYPTO_SYMS_BTC, {"lookback": 50, "entry_z": 2.5, "exit_z": 0.5, "rsi_confirm": True},
           "Z-Score MR BTC 宽入场"),
    _entry(41, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-BTC-LogRet",
           CRYPTO_SYMS_BTC, {"lookback": 40, "entry_z": 2.0, "use_log_returns": True},
           "Z-Score 对数收益率"),
    _entry(42, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-ETH",
           CRYPTO_SYMS_ETH, {"lookback": 35, "entry_z": 2.0, "rsi_confirm": True},
           "Z-Score ETH"),
    _entry(43, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-SOL",
           CRYPTO_SYMS_SOL, {"lookback": 25, "entry_z": 1.8},
           "Z-Score SOL"),
    _entry(44, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-BNB",
           CRYPTO_SYMS_BNB, {"lookback": 30, "entry_z": 2.0},
           "Z-Score BNB"),
    _entry(45, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-NoRSI",
           CRYPTO_SYMS_BTC, {"lookback": 40, "entry_z": 2.2, "rsi_confirm": False},
           "Z-Score 纯统计 (无RSI)"),
    _entry(46, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-XRP",
           CRYPTO_SYMS_XRP, {"lookback": 30, "entry_z": 1.8, "rsi_confirm": True},
           "Z-Score XRP"),
    _entry(47, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-Multi",
           CRYPTO_SYMS_ALL, {"lookback": 35, "entry_z": 2.0},
           "Z-Score 多品种"),
    _entry(48, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-BTC-Fast",
           CRYPTO_SYMS_BTC, {"lookback": 15, "entry_z": 1.5, "exit_z": 0.2, "max_hold_bars": 40},
           "Z-Score BTC 快速MR"),

    # ─── Regime Filter (49-56) ───
    _entry(49, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-BTC-Standard",
           CRYPTO_SYMS_BTC, {},
           "体制过滤 BTC 标准"),
    _entry(50, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-BTC-Sensitive",
           CRYPTO_SYMS_BTC, {"adx_trend_threshold": 20, "bb_squeeze_pct": 0.04, "bb_expand_pct": 0.06},
           "体制过滤 BTC 高灵敏"),
    _entry(51, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-ETH",
           CRYPTO_SYMS_ETH, {"adx_trend_threshold": 22},
           "体制过滤 ETH"),
    _entry(52, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-SOL",
           CRYPTO_SYMS_SOL, {"adx_trend_threshold": 20, "bb_squeeze_pct": 0.05},
           "体制过滤 SOL"),
    _entry(53, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-Multi",
           CRYPTO_SYMS_ALL, {},
           "体制过滤 多品种"),
    _entry(54, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-BTC-FastMA",
           CRYPTO_SYMS_BTC, {"trend_ma_fast": 5, "trend_ma_slow": 15, "mr_rsi_period": 10},
           "体制过滤 BTC 快参"),
    _entry(55, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-BTC-SlowMA",
           CRYPTO_SYMS_BTC, {"trend_ma_fast": 20, "trend_ma_slow": 50, "mr_rsi_period": 20},
           "体制过滤 BTC 慢参"),
    _entry(56, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-BNB",
           CRYPTO_SYMS_BNB, {},
           "体制过滤 BNB"),

    # ─── OrderFlow / VWAP (57-64) ───
    _entry(57, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-BTC-Standard",
           CRYPTO_SYMS_BTC, {},
           "订单流 BTC 标准 VWAP+OBV"),
    _entry(58, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-BTC-VWAPOnly",
           CRYPTO_SYMS_BTC, {"obv_divergence": False, "taker_weight": 0},
           "纯 VWAP 回归 BTC"),
    _entry(59, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-BTC-OBVFocus",
           CRYPTO_SYMS_BTC, {"vwap_dev_entry": 3.0, "obv_divergence": True, "taker_weight": 0.5},
           "OBV 背离重点 BTC"),
    _entry(60, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-ETH",
           CRYPTO_SYMS_ETH, {},
           "订单流 ETH"),
    _entry(61, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-SOL",
           CRYPTO_SYMS_SOL, {"vwap_period": 15, "vwap_dev_entry": 1.5},
           "订单流 SOL"),
    _entry(62, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-BNB",
           CRYPTO_SYMS_BNB, {},
           "订单流 BNB"),
    _entry(63, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-Taker",
           CRYPTO_SYMS_BTC, {"taker_ratio_threshold": 0.55, "taker_weight": 2.0, "vwap_dev_entry": 2.5},
           "Taker Ratio 重权 BTC"),
    _entry(64, "strategy.templates.orderflow.OrderFlowStrategy", "OrderFlow-Multi",
           CRYPTO_SYMS_ALL, {},
           "订单流 多品种"),

    # ─── Multi-Indicator Voting (65-72) ───
    _entry(65, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-BTC-Equal",
           CRYPTO_SYMS_BTC, {"min_score": 2.5},
           "多指标等权 BTC"),
    _entry(66, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-BTC-RSIHeavy",
           CRYPTO_SYMS_BTC, {"rsi_weight": 2.0, "macd_weight": 1.0, "stoch_weight": 0.5, "cci_weight": 0.5, "min_score": 2.0},
           "多指标 RSI 重权 BTC"),
    _entry(67, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-BTC-MACDHeavy",
           CRYPTO_SYMS_BTC, {"rsi_weight": 0.5, "macd_weight": 2.0, "stoch_weight": 1.0, "cci_weight": 0.5, "min_score": 2.0},
           "多指标 MACD 重权 BTC"),
    _entry(68, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-ETH",
           CRYPTO_SYMS_ETH, {"min_score": 2.0},
           "多指标 ETH"),
    _entry(69, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-SOL",
           CRYPTO_SYMS_SOL, {"min_score": 2.0, "rsi_oversold": 25, "rsi_overbought": 75},
           "多指标 SOL"),
    _entry(70, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-BTC-Strict",
           CRYPTO_SYMS_BTC, {"min_score": 3.5, "rsi_oversold": 20, "rsi_overbought": 80},
           "多指标 严格过滤 BTC"),
    _entry(71, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-BNB",
           CRYPTO_SYMS_BNB, {"min_score": 2.0},
           "多指标 BNB"),
    _entry(72, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-Multi",
           CRYPTO_SYMS_ALL, {"min_score": 2.5},
           "多指标 多品种"),

    # ─── Channel Breakout Donchian/Keltner (73-80) ───
    _entry(73, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-BTC-20",
           CRYPTO_SYMS_BTC, {"channel_type": "donchian", "entry_period": 20, "exit_period": 10},
           "Donchian通道 BTC 20/10 (海龟系统)"),
    _entry(74, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-BTC-55",
           CRYPTO_SYMS_BTC, {"channel_type": "donchian", "entry_period": 55, "exit_period": 20},
           "Donchian通道 BTC 55/20 (海龟长周期)"),
    _entry(75, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Keltner-BTC",
           CRYPTO_SYMS_BTC, {"channel_type": "keltner", "entry_period": 20, "keltner_mult": 2.0},
           "Keltner通道 BTC"),
    _entry(76, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Keltner-BTC-Wide",
           CRYPTO_SYMS_BTC, {"channel_type": "keltner", "entry_period": 20, "keltner_mult": 3.0},
           "Keltner宽通道 BTC"),
    _entry(77, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-ETH",
           CRYPTO_SYMS_ETH, {"channel_type": "donchian", "entry_period": 20, "exit_period": 10},
           "Donchian通道 ETH"),
    _entry(78, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Keltner-ETH",
           CRYPTO_SYMS_ETH, {"channel_type": "keltner", "entry_period": 15, "keltner_mult": 2.0},
           "Keltner通道 ETH"),
    _entry(79, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-SOL",
           CRYPTO_SYMS_SOL, {"channel_type": "donchian", "entry_period": 15, "exit_period": 7},
           "Donchian通道 SOL"),
    _entry(80, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Channel-Multi",
           CRYPTO_SYMS_ALL, {"channel_type": "donchian", "entry_period": 25, "exit_period": 12},
           "Donchian通道 多品种"),

    # ─── Momentum Rotation / Dual Momentum (81-88) ───
    _entry(81, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-BTC-20d",
           CRYPTO_SYMS_BTC, {"lookback": 20, "momentum_type": "tsmom", "vol_adjust": True},
           "TSMOM BTC 20期 (Moskowitz 2012)"),
    _entry(82, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-BTC-60d",
           CRYPTO_SYMS_BTC, {"lookback": 60, "momentum_type": "tsmom", "holding_period": 20},
           "TSMOM BTC 60期 长周期"),
    _entry(83, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "DualMom-BTC",
           CRYPTO_SYMS_BTC, {"momentum_type": "dual", "absolute_threshold": 0.02, "lookback": 30},
           "Dual Momentum BTC (Antonacci)"),
    _entry(84, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "DualMom-ETH",
           CRYPTO_SYMS_ETH, {"momentum_type": "dual", "absolute_threshold": 0.02, "lookback": 25},
           "Dual Momentum ETH"),
    _entry(85, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-ETH",
           CRYPTO_SYMS_ETH, {"lookback": 20, "momentum_type": "tsmom"},
           "TSMOM ETH"),
    _entry(86, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "MomRot-SOL",
           CRYPTO_SYMS_SOL, {"lookback": 15, "momentum_type": "tsmom", "holding_period": 5},
           "动量轮动 SOL"),
    _entry(87, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "DualMom-Multi",
           CRYPTO_SYMS_ALL, {"momentum_type": "dual", "absolute_threshold": 0.015},
           "Dual Momentum 多品种"),
    _entry(88, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-Multi-VolAdj",
           CRYPTO_SYMS_ALL, {"lookback": 30, "vol_adjust": True},
           "TSMOM 波动率调整 多品种"),

    # ─── EMA-Derivative SOTA (89-96) — 学术论文 Return 3906%, Sharpe 1.50 ───
    _entry(89, "strategy.templates.ema_derivative.EMADerivativeStrategy", "EMADeriv-BTC-21",
           CRYPTO_SYMS_BTC, {"ema_period": 21, "deriv_smooth": 5, "trailing_stop_atr_mult": 3.0},
           "EMA变化率 BTC 标准 (论文级)"),
    _entry(90, "strategy.templates.ema_derivative.EMADerivativeStrategy", "EMADeriv-BTC-Fast",
           CRYPTO_SYMS_BTC, {"ema_period": 12, "deriv_smooth": 3, "trailing_stop_atr_mult": 2.5},
           "EMA变化率 BTC 快速"),
    _entry(91, "strategy.templates.ema_derivative.EMADerivativeStrategy", "EMADeriv-BTC-Slow",
           CRYPTO_SYMS_BTC, {"ema_period": 50, "deriv_smooth": 8, "trailing_stop_atr_mult": 4.0},
           "EMA变化率 BTC 慢速 (低频交易)"),
    _entry(92, "strategy.templates.ema_derivative.EMADerivativeStrategy", "EMADeriv-ETH",
           CRYPTO_SYMS_ETH, {"ema_period": 21, "deriv_smooth": 5},
           "EMA变化率 ETH"),
    _entry(93, "strategy.templates.ema_derivative.EMADerivativeStrategy", "EMADeriv-SOL",
           CRYPTO_SYMS_SOL, {"ema_period": 15, "deriv_smooth": 4},
           "EMA变化率 SOL"),
    _entry(94, "strategy.templates.ema_derivative.EMADerivativeStrategy", "EMADeriv-Multi",
           CRYPTO_SYMS_ALL, {"ema_period": 21, "deriv_smooth": 5},
           "EMA变化率 多品种"),

    # ─── Alpha TRIX SOTA (95-100) — 三层验证趋势跟踪 ───
    _entry(95, "strategy.templates.trix_alpha.TrixAlphaStrategy", "TRIX-BTC-Standard",
           CRYPTO_SYMS_BTC, {"trix_period": 18, "chop_threshold": 55, "adx_threshold": 20},
           "Alpha TRIX BTC 标准 (三层验证)"),
    _entry(96, "strategy.templates.trix_alpha.TrixAlphaStrategy", "TRIX-BTC-Sensitive",
           CRYPTO_SYMS_BTC, {"trix_period": 12, "chop_threshold": 50, "adx_threshold": 15},
           "Alpha TRIX BTC 高灵敏"),
    _entry(97, "strategy.templates.trix_alpha.TrixAlphaStrategy", "TRIX-ETH",
           CRYPTO_SYMS_ETH, {"trix_period": 18, "chop_threshold": 55, "adx_threshold": 20},
           "Alpha TRIX ETH"),
    _entry(98, "strategy.templates.trix_alpha.TrixAlphaStrategy", "TRIX-SOL",
           CRYPTO_SYMS_SOL, {"trix_period": 15, "chop_threshold": 50, "adx_threshold": 18},
           "Alpha TRIX SOL"),
    _entry(99, "strategy.templates.trix_alpha.TrixAlphaStrategy", "TRIX-BNB",
           CRYPTO_SYMS_BNB, {"trix_period": 18, "chop_threshold": 55},
           "Alpha TRIX BNB"),
    _entry(100, "strategy.templates.trix_alpha.TrixAlphaStrategy", "TRIX-Multi",
           CRYPTO_SYMS_ALL, {"trix_period": 18, "chop_threshold": 55, "adx_threshold": 20},
           "Alpha TRIX 多品种"),
]


# ══════════════════════════════════════════════
# FUTURES STRATEGIES (accounts 101-200)
# ══════════════════════════════════════════════

FUTURES_CATALOG: list[dict[str, Any]] = [
    # ─── CTA Trend 唐奇安 (101-110) ───
    _entry(101, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-RB-20/10",
           FUT_RB, {"entry_period": 20, "exit_period": 10},
           "CTA趋势 螺纹钢 20/10"),
    _entry(102, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-RB-55/20",
           FUT_RB, {"entry_period": 55, "exit_period": 20},
           "CTA趋势 螺纹钢 55/20 (海龟长周期)"),
    _entry(103, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-I-20/10",
           FUT_I, {"entry_period": 20, "exit_period": 10},
           "CTA趋势 铁矿石"),
    _entry(104, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-AU-30/15",
           FUT_AU, {"entry_period": 30, "exit_period": 15},
           "CTA趋势 黄金"),
    _entry(105, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-AG-20/10",
           FUT_AG, {"entry_period": 20, "exit_period": 10},
           "CTA趋势 白银"),
    _entry(106, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-CU-20/10",
           FUT_CU, {"entry_period": 20, "exit_period": 10},
           "CTA趋势 铜"),
    _entry(107, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-AL-25/12",
           FUT_AL, {"entry_period": 25, "exit_period": 12},
           "CTA趋势 铝"),
    _entry(108, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-NI-20/10",
           FUT_NI, {"entry_period": 20, "exit_period": 10},
           "CTA趋势 镍"),
    _entry(109, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-IF-30/15",
           FUT_IF, {"entry_period": 30, "exit_period": 15},
           "CTA趋势 IF股指"),
    _entry(110, "strategy.futures.cta_trend.CTATrendStrategy", "CTA-TA-20/10",
           FUT_TA, {"entry_period": 20, "exit_period": 10},
           "CTA趋势 PTA"),

    # ─── R-Breaker (111-116) ───
    _entry(111, "strategy.futures.rbreaker.RBreakerStrategy", "RBreaker-RB",
           FUT_RB, {},
           "R-Breaker 螺纹钢 (经典日内反转)"),
    _entry(112, "strategy.futures.rbreaker.RBreakerStrategy", "RBreaker-I",
           FUT_I, {},
           "R-Breaker 铁矿石"),
    _entry(113, "strategy.futures.rbreaker.RBreakerStrategy", "RBreaker-AU",
           FUT_AU, {},
           "R-Breaker 黄金"),
    _entry(114, "strategy.futures.rbreaker.RBreakerStrategy", "RBreaker-CU",
           FUT_CU, {},
           "R-Breaker 铜"),
    _entry(115, "strategy.futures.rbreaker.RBreakerStrategy", "RBreaker-IF",
           FUT_IF, {},
           "R-Breaker IF股指"),
    _entry(116, "strategy.futures.rbreaker.RBreakerStrategy", "RBreaker-AG",
           FUT_AG, {},
           "R-Breaker 白银"),

    # ─── Dual MA (117-122) ───
    _entry(117, "strategy.futures.dual_ma.FuturesDualMAStrategy", "DualMA-RB-5/20",
           FUT_RB, {"fast_period": 5, "slow_period": 20},
           "双均线 螺纹钢 5/20"),
    _entry(118, "strategy.futures.dual_ma.FuturesDualMAStrategy", "DualMA-RB-10/40",
           FUT_RB, {"fast_period": 10, "slow_period": 40},
           "双均线 螺纹钢 10/40"),
    _entry(119, "strategy.futures.dual_ma.FuturesDualMAStrategy", "DualMA-I-5/20",
           FUT_I, {"fast_period": 5, "slow_period": 20},
           "双均线 铁矿石 5/20"),
    _entry(120, "strategy.futures.dual_ma.FuturesDualMAStrategy", "DualMA-AU-10/30",
           FUT_AU, {"fast_period": 10, "slow_period": 30},
           "双均线 黄金 10/30"),
    _entry(121, "strategy.futures.dual_ma.FuturesDualMAStrategy", "DualMA-CU-5/20",
           FUT_CU, {"fast_period": 5, "slow_period": 20},
           "双均线 铜 5/20"),
    _entry(122, "strategy.futures.dual_ma.FuturesDualMAStrategy", "DualMA-IF-10/30",
           FUT_IF, {"fast_period": 10, "slow_period": 30},
           "双均线 IF股指 10/30"),

    # ─── Bollinger MR (123-128) ───
    _entry(123, "strategy.futures.bollinger_mr.BollingerMRStrategy", "BollingerMR-RB",
           FUT_RB, {"bb_period": 20, "bb_std": 2.0},
           "Bollinger均值回归 螺纹钢"),
    _entry(124, "strategy.futures.bollinger_mr.BollingerMRStrategy", "BollingerMR-I",
           FUT_I, {"bb_period": 20, "bb_std": 2.0},
           "Bollinger均值回归 铁矿石"),
    _entry(125, "strategy.futures.bollinger_mr.BollingerMRStrategy", "BollingerMR-AU",
           FUT_AU, {"bb_period": 25, "bb_std": 2.5},
           "Bollinger均值回归 黄金"),
    _entry(126, "strategy.futures.bollinger_mr.BollingerMRStrategy", "BollingerMR-CU",
           FUT_CU, {"bb_period": 20, "bb_std": 2.0},
           "Bollinger均值回归 铜"),
    _entry(127, "strategy.futures.bollinger_mr.BollingerMRStrategy", "BollingerMR-AG",
           FUT_AG, {"bb_period": 20, "bb_std": 2.0},
           "Bollinger均值回归 白银"),
    _entry(128, "strategy.futures.bollinger_mr.BollingerMRStrategy", "BollingerMR-IF",
           FUT_IF, {"bb_period": 20, "bb_std": 2.0},
           "Bollinger均值回归 IF股指"),

    # ─── Vol Breakout (129-134) ───
    _entry(129, "strategy.futures.vol_breakout.VolBreakoutStrategy", "VolBreak-RB",
           FUT_RB, {},
           "波动率突破 螺纹钢"),
    _entry(130, "strategy.futures.vol_breakout.VolBreakoutStrategy", "VolBreak-I",
           FUT_I, {},
           "波动率突破 铁矿石"),
    _entry(131, "strategy.futures.vol_breakout.VolBreakoutStrategy", "VolBreak-AU",
           FUT_AU, {},
           "波动率突破 黄金"),
    _entry(132, "strategy.futures.vol_breakout.VolBreakoutStrategy", "VolBreak-CU",
           FUT_CU, {},
           "波动率突破 铜"),
    _entry(133, "strategy.futures.vol_breakout.VolBreakoutStrategy", "VolBreak-MA",
           FUT_MA, {},
           "波动率突破 甲醇"),
    _entry(134, "strategy.futures.vol_breakout.VolBreakoutStrategy", "VolBreak-IF",
           FUT_IF, {},
           "波动率突破 IF股指"),

    # ─── Volume Price (135-140) ───
    _entry(135, "strategy.futures.volume_price.VolumePriceStrategy", "VolPrice-RB",
           FUT_RB, {},
           "量价策略 螺纹钢"),
    _entry(136, "strategy.futures.volume_price.VolumePriceStrategy", "VolPrice-I",
           FUT_I, {},
           "量价策略 铁矿石"),
    _entry(137, "strategy.futures.volume_price.VolumePriceStrategy", "VolPrice-AU",
           FUT_AU, {},
           "量价策略 黄金"),
    _entry(138, "strategy.futures.volume_price.VolumePriceStrategy", "VolPrice-CU",
           FUT_CU, {},
           "量价策略 铜"),
    _entry(139, "strategy.futures.volume_price.VolumePriceStrategy", "VolPrice-AG",
           FUT_AG, {},
           "量价策略 白银"),
    _entry(140, "strategy.futures.volume_price.VolumePriceStrategy", "VolPrice-IF",
           FUT_IF, {},
           "量价策略 IF股指"),

    # ─── Supertrend 期货版 (141-148) ───
    _entry(141, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-RB",
           FUT_RB, {"atr_period": 10, "multiplier": 3.0},
           "Supertrend 螺纹钢"),
    _entry(142, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-I",
           FUT_I, {"atr_period": 10, "multiplier": 3.0},
           "Supertrend 铁矿石"),
    _entry(143, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-AU",
           FUT_AU, {"atr_period": 14, "multiplier": 3.5},
           "Supertrend 黄金"),
    _entry(144, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-CU",
           FUT_CU, {"atr_period": 10, "multiplier": 3.0},
           "Supertrend 铜"),
    _entry(145, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-IF",
           FUT_IF, {"atr_period": 10, "multiplier": 3.0, "adx_threshold": 22},
           "Supertrend IF股指"),
    _entry(146, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-NI",
           FUT_NI, {"atr_period": 10, "multiplier": 3.0},
           "Supertrend 镍"),
    _entry(147, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-ZN",
           FUT_ZN, {"atr_period": 12, "multiplier": 3.0},
           "Supertrend 锌"),
    _entry(148, "strategy.templates.supertrend.SupertrendStrategy", "Supertrend-PP",
           FUT_PP, {"atr_period": 10, "multiplier": 2.5},
           "Supertrend 聚丙烯"),

    # ─── Kalman 期货版 (149-154) ───
    _entry(149, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-RB",
           FUT_RB, {"process_noise": 0.01, "measurement_noise": 0.5, "velocity_threshold": 0.001},
           "Kalman滤波 螺纹钢"),
    _entry(150, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-I",
           FUT_I, {"process_noise": 0.01, "measurement_noise": 0.5, "velocity_threshold": 0.001},
           "Kalman滤波 铁矿石"),
    _entry(151, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-AU",
           FUT_AU, {"process_noise": 0.005, "measurement_noise": 0.8, "velocity_threshold": 0.0005},
           "Kalman滤波 黄金 (慢速)"),
    _entry(152, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-CU",
           FUT_CU, {"process_noise": 0.01, "measurement_noise": 0.5, "velocity_threshold": 0.001},
           "Kalman滤波 铜"),
    _entry(153, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-IF",
           FUT_IF, {"process_noise": 0.008, "measurement_noise": 0.6, "velocity_threshold": 0.0008},
           "Kalman滤波 IF股指"),
    _entry(154, "strategy.templates.kalman_trend.KalmanTrendStrategy", "Kalman-AG",
           FUT_AG, {"process_noise": 0.012, "measurement_noise": 0.4, "velocity_threshold": 0.0012},
           "Kalman滤波 白银"),

    # ─── Regime Filter 期货版 (155-162) ───
    _entry(155, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-RB",
           FUT_RB, {},
           "体制过滤 螺纹钢"),
    _entry(156, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-I",
           FUT_I, {},
           "体制过滤 铁矿石"),
    _entry(157, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-AU",
           FUT_AU, {"adx_trend_threshold": 20},
           "体制过滤 黄金"),
    _entry(158, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-CU",
           FUT_CU, {},
           "体制过滤 铜"),
    _entry(159, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-IF",
           FUT_IF, {},
           "体制过滤 IF股指"),
    _entry(160, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-AG",
           FUT_AG, {},
           "体制过滤 白银"),
    _entry(161, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-MA",
           FUT_MA, {},
           "体制过滤 甲醇"),
    _entry(162, "strategy.templates.regime_filter.RegimeFilterStrategy", "Regime-NI",
           FUT_NI, {},
           "体制过滤 镍"),

    # ─── Adaptive Trend 期货版 (163-170) ───
    _entry(163, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-RB",
           FUT_RB, {"ma_type": "kama", "fast_period": 8, "slow_period": 25},
           "Kaufman AMA 螺纹钢"),
    _entry(164, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-I",
           FUT_I, {"ma_type": "kama", "fast_period": 8, "slow_period": 25},
           "Kaufman AMA 铁矿石"),
    _entry(165, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-RB",
           FUT_RB, {"ma_type": "hull", "fast_period": 10, "slow_period": 24},
           "Hull MA 螺纹钢"),
    _entry(166, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-AU",
           FUT_AU, {"ma_type": "hull", "fast_period": 12, "slow_period": 30},
           "Hull MA 黄金"),
    _entry(167, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "DEMA-CU",
           FUT_CU, {"ma_type": "dema", "fast_period": 10, "slow_period": 25},
           "DEMA 铜"),
    _entry(168, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-IF",
           FUT_IF, {"ma_type": "kama", "fast_period": 10, "slow_period": 30},
           "Kaufman AMA IF股指"),
    _entry(169, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "Hull-IF",
           FUT_IF, {"ma_type": "hull", "fast_period": 10, "slow_period": 25},
           "Hull MA IF股指"),
    _entry(170, "strategy.templates.adaptive_trend.AdaptiveTrendStrategy", "KAMA-AG",
           FUT_AG, {"ma_type": "kama", "fast_period": 8, "slow_period": 22},
           "Kaufman AMA 白银"),

    # ─── Z-Score 期货版 (171-176) ───
    _entry(171, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-RB",
           FUT_RB, {"lookback": 40, "entry_z": 2.0},
           "Z-Score 均值回归 螺纹钢"),
    _entry(172, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-I",
           FUT_I, {"lookback": 35, "entry_z": 2.0},
           "Z-Score 均值回归 铁矿石"),
    _entry(173, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-AU",
           FUT_AU, {"lookback": 50, "entry_z": 2.5},
           "Z-Score 均值回归 黄金"),
    _entry(174, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-CU",
           FUT_CU, {"lookback": 40, "entry_z": 2.0},
           "Z-Score 均值回归 铜"),
    _entry(175, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-IF",
           FUT_IF, {"lookback": 30, "entry_z": 1.8},
           "Z-Score 均值回归 IF股指"),
    _entry(176, "strategy.templates.stat_arb.StatArbStrategy", "ZScore-AG",
           FUT_AG, {"lookback": 35, "entry_z": 2.0},
           "Z-Score 均值回归 白银"),

    # ─── Vol Target 期货版 (177-182) ───
    _entry(177, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-RB",
           FUT_RB, {"target_vol": 0.15, "lookback": 20},
           "波动率目标 螺纹钢"),
    _entry(178, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-I",
           FUT_I, {"target_vol": 0.15, "lookback": 20},
           "波动率目标 铁矿石"),
    _entry(179, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-AU",
           FUT_AU, {"target_vol": 0.10, "lookback": 30},
           "波动率目标 黄金"),
    _entry(180, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-CU",
           FUT_CU, {"target_vol": 0.15, "lookback": 20},
           "波动率目标 铜"),
    _entry(181, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-IF",
           FUT_IF, {"target_vol": 0.12, "lookback": 20},
           "波动率目标 IF股指"),
    _entry(182, "strategy.templates.vol_target.VolTargetStrategy", "VolTarget-AG",
           FUT_AG, {"target_vol": 0.15, "lookback": 20},
           "波动率目标 白银"),

    # ─── Multi-Indicator 期货版 (183-188) ───
    _entry(183, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-RB",
           FUT_RB, {"min_score": 2.5},
           "多指标 螺纹钢"),
    _entry(184, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-I",
           FUT_I, {"min_score": 2.5},
           "多指标 铁矿石"),
    _entry(185, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-AU",
           FUT_AU, {"min_score": 2.0, "rsi_oversold": 25, "rsi_overbought": 75},
           "多指标 黄金"),
    _entry(186, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-CU",
           FUT_CU, {"min_score": 2.5},
           "多指标 铜"),
    _entry(187, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-IF",
           FUT_IF, {"min_score": 2.0},
           "多指标 IF股指"),
    _entry(188, "strategy.templates.multi_indicator.MultiIndicatorStrategy", "MultiInd-IC",
           FUT_IC, {"min_score": 2.0},
           "多指标 IC中证500"),

    # ─── Channel Breakout 期货版 (189-194) ───
    _entry(189, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-RB",
           FUT_RB, {"channel_type": "donchian", "entry_period": 20, "exit_period": 10},
           "Donchian通道 螺纹钢"),
    _entry(190, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Keltner-RB",
           FUT_RB, {"channel_type": "keltner", "entry_period": 20, "keltner_mult": 2.0},
           "Keltner通道 螺纹钢"),
    _entry(191, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-AU",
           FUT_AU, {"channel_type": "donchian", "entry_period": 25, "exit_period": 12},
           "Donchian通道 黄金"),
    _entry(192, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Keltner-CU",
           FUT_CU, {"channel_type": "keltner", "entry_period": 20, "keltner_mult": 2.5},
           "Keltner通道 铜"),
    _entry(193, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Donchian-IF",
           FUT_IF, {"channel_type": "donchian", "entry_period": 20, "exit_period": 10},
           "Donchian通道 IF股指"),
    _entry(194, "strategy.templates.channel_breakout.ChannelBreakoutStrategy", "Keltner-IF",
           FUT_IF, {"channel_type": "keltner", "entry_period": 15, "keltner_mult": 2.0},
           "Keltner通道 IF股指"),

    # ─── Momentum Rotation 期货版 (195-200) ───
    _entry(195, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-RB",
           FUT_RB, {"lookback": 20, "momentum_type": "tsmom"},
           "TSMOM 螺纹钢"),
    _entry(196, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "DualMom-RB",
           FUT_RB, {"momentum_type": "dual", "absolute_threshold": 0.02},
           "Dual Momentum 螺纹钢"),
    _entry(197, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-AU",
           FUT_AU, {"lookback": 30, "momentum_type": "tsmom"},
           "TSMOM 黄金"),
    _entry(198, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "DualMom-AU",
           FUT_AU, {"momentum_type": "dual", "absolute_threshold": 0.015},
           "Dual Momentum 黄金"),
    _entry(199, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "TSMOM-IF",
           FUT_IF, {"lookback": 20, "momentum_type": "tsmom"},
           "TSMOM IF股指"),
    _entry(200, "strategy.templates.momentum_rotation.MomentumRotationStrategy", "DualMom-IF",
           FUT_IF, {"momentum_type": "dual", "absolute_threshold": 0.02},
           "Dual Momentum IF股指"),
]


FULL_CATALOG = CRYPTO_CATALOG + FUTURES_CATALOG


def get_catalog(market: str | None = None) -> list[dict[str, Any]]:
    if market == "crypto":
        return CRYPTO_CATALOG
    elif market == "futures":
        return FUTURES_CATALOG
    return FULL_CATALOG
